name: numb3r3
description: 推荐系统攻城狮
url: http://numb3r3.com
markdown: kramdown
highlighter: rough
permalink: /:year/:month/:day/:title.html
author: felix
email: wangfelix87@gmail.com
safe: true
paginate: 16
auto: true
keywords: [Machine Learning,机器学习,Algorithm,算法,Math,数学,推荐系统,Recommender System,Distributed,分布式]
github: hezila
duoshuo: wangfengmadking@gmail.com
bshare: 645356e4-b1d6-45ae-bab7-3e7185bdc483
excerpt_separator: "" # to workaround highlight tag was never closed
