name: numb3r3
description: 推荐系统攻城狮
url: http://numb3r3.com
markdown: kramdown
highlighter: rouge
lang: en
permalink: /:year/:month/:day/:title.html
tagline: ':(){:|:&amp;};:'
author: felix
email: wangfelix87@gmail.com
safe: true
paginate: 16
auto: true
keywords: [Machine Learning,机器学习,Algorithm,算法,Math,数学,推荐系统,Recommender System,Distributed,分布式]
github: hezila
excerpt_separator: "" # to workaround highlight tag was never closed
